In [1]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/99/2b/f7114983d84303019385d93d24d729aedba67be7e083286f114188943cf3/numpy-1.26.3-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------- -------------------------- 20.5/61.2 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.2 kB 435.7 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.2 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 271.1 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? et

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 466, in read
    s = self.fp.read(amt)
        ^^^^^

In [6]:
pip install pandas

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     --------------------------------- ------ 51.2/61.2 kB 1.3 MB/s eta 0:00:01
     ---------------------------------------- 61.2/61.2 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.6 MB 1.7 MB/s eta 0:00:07
   ---------------------------------------- 0.1/11.6 MB 1.3 MB/s eta 0:00:09
   ---------------------------------------- 0.1/11.6 MB 1.3 MB/s eta 0:00:09
    --------------------------------------- 0.2/11.6 MB 833.5 kB/s eta 0:00:14
    --------------------------------------- 0.2/11.6 MB 1.1 MB/s eta 0:00:11
    --------------------------------------- 0.3/11.6 MB 1.1 MB/s eta 0:00:10
   - -------------------------------------- 0.3/11.6 MB 1.0 MB/s eta 0:00:11
   - -------------------------------------- 0.5/11.6 MB 1.2 MB/s eta 0:00:10
   - -------------------------------------- 0.6/11.6 MB 1.4 MB/s eta 0:00:08
   

In [5]:
!python.exe -m pip install --upgrade pip

  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/15/aa/3f4c7bcee2057a76562a5b33ecbd199be08cdb4443a02e26bd2c3cf6fc39/pip-23.3.2-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 108.9 kB/s eta 0:00:20
    --------------------------------------- 0.0/2.1 MB 108.9 kB/s eta 0:00:20
    --------------------------------------- 0.0/2.1 MB 108.9 kB/s eta 0:00:20
    --------------------------------------- 0.0/2.1 MB 108.9 kB/s eta 0:00:20
    --------------------------------------- 0.0/2.1 MB 108.9 kB/s eta 0:00:20
    --------------------------------------- 0.0/2.1 MB 54.6 kB/s eta 0:00:38
   -- ------------------------------------- 0.1/2.1 MB 207.7 kB/s

In [7]:
!pip list

Package           Version
----------------- -------
asttokens         2.4.0
backcall          0.2.0
colorama          0.4.6
comm              0.1.4
customtkinter     5.2.0
darkdetect        0.8.0
debugpy           1.8.0
decorator         5.1.1
executing         1.2.0
ipykernel         6.25.2
ipython           8.15.0
jedi              0.19.0
jupyter_client    8.3.1
jupyter_core      5.3.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.8
numpy             1.26.3
packaging         23.1
pandas            2.2.0
parso             0.8.3
pickleshare       0.7.5
pip               23.3.2
platformdirs      3.10.0
prompt-toolkit    3.0.39
psutil            5.9.5
pure-eval         0.2.2
Pygments          2.16.1
python-dateutil   2.8.2
pytz              2024.1
pywin32           306
pyzmq             25.1.1
setuptools        65.5.0
six               1.16.0
stack-data        0.6.2
tornado           6.3.3
traitlets         5.10.0
tzdata            2023.4
wcwidth           0.2.6


In [87]:
import pandas as pd
df = pd.read_csv('vgsales.csv')
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [88]:
df.shape

(16598, 11)

In [91]:
df.size, df.ndim

(182578, 2)

In [3]:
df.describe()

Rank          Year      NA_Sales      EU_Sales      JP_Sales  \
count  16598.000000  16327.000000  16598.000000  16598.000000  16598.000000   
mean    8300.605254   2006.406443      0.264667      0.146652      0.077782   
std     4791.853933      5.828981      0.816683      0.505351      0.309291   
min        1.000000   1980.000000      0.000000      0.000000      0.000000   
25%     4151.250000   2003.000000      0.000000      0.000000      0.000000   
50%     8300.500000   2007.000000      0.080000      0.020000      0.000000   
75%    12449.750000   2010.000000      0.240000      0.110000      0.040000   
max    16600.000000   2020.000000     41.490000     29.020000     10.220000   

        Other_Sales  Global_Sales  
count  16598.000000  16598.000000  
mean       0.048063      0.537441  
std        0.188588      1.555028  
min        0.000000      0.010000  
25%        0.000000      0.060000  
50%        0.010000      0.170000  
75%        0.040000      0.470000  
max       10.570000     82.740000

In [7]:
df.values

array([[1, 'Wii Sports', 'Wii', ..., 3.77, 8.46, 82.74],
       [2, 'Super Mario Bros.', 'NES', ..., 6.81, 0.77, 40.24],
       [3, 'Mario Kart Wii', 'Wii', ..., 3.79, 3.31, 35.82],
       ...,
       [16598, 'SCORE International Baja 1000: The Official Game', 'PS2',
        ..., 0.0, 0.0, 0.01],
       [16599, 'Know How 2', 'DS', ..., 0.0, 0.0, 0.01],
       [16600, 'Spirits & Spells', 'GBA', ..., 0.0, 0.0, 0.01]],
      dtype=object)

# Numpy DataTypes and Attributes

In [41]:
# import mumpy
import numpy as np
ai = np.array([1,2,3,4])
ai

array([1, 2, 3, 4])

In [42]:
type(ai)

numpy.ndarray

In [44]:
ai.size

4

In [45]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
a2.shape

(2, 3)

In [47]:
a3 = np.array([[[1,2,3],
[4,5,6],
[7,8,9]],
[[10,11,12],
[13,14,15],
[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
a2.size, a3.size, ai.size

(6, 18, 4)

In [49]:
a2.shape, a3.shape, ai.shape

((2, 3), (2, 3, 3), (4,))

In [50]:
a3.ndim

3

In [51]:
a4 = np.array([1,2,3,6])
a4

array([1, 2, 3, 6])

In [52]:
a4.shape

(4,)

In [56]:
# addtitiuon
add_ai = ai + 1
ai, add_ai

(array([1, 2, 3, 4]), array([2, 3, 4, 5]))

In [57]:
mulltiply_ai = ai * 2
ai, mulltiply_ai

(array([1, 2, 3, 4]), array([2, 4, 6, 8]))

In [62]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
# slice numpy array
a2[1:2, 1]

array([5])

In [78]:
y1 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[7,8,9],[3,5,3]])
y3 = np.dot(y1,y2.T)
y3, y1

(array([[ 50,  22],
        [122,  55]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [80]:
data = np.array([[1, 2, -1], [4, -5, 6], [7, 8, 9]]) 
positive_values = np.clip(data, 0, np.inf)
data, positive_values

(array([[ 1,  2, -1],
        [ 4, -5,  6],
        [ 7,  8,  9]]),
 array([[1., 2., 0.],
        [4., 0., 6.],
        [7., 8., 9.]]))

In [75]:
x = np.random.rand(3, 3)
x, x.shape, x.ndim

(array([[0.07511457, 0.57144212, 0.25245619],
        [0.02211259, 0.7962604 , 0.40156732],
        [0.15768325, 0.47228911, 0.24471606]]),
 (3, 3),
 2)

In [60]:
# array broad cast
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])

result = x + y
result

array([[11, 22, 33],
       [14, 25, 36]])

In [81]:
# Addition 
# Element-wise Addition:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2
result

array([5, 7, 9])

In [82]:
# matrices operation
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)
result

array([[19, 22],
       [43, 50]])

In [83]:
# Reshaping 1D array
arr = np.array([1, 2, 3, 4, 5])

reshaped_arr = arr.reshape((1, 5))
reshaped_arr

array([[1, 2, 3, 4, 5]])

In [84]:
# stacking arrays vertically
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked_arr = np.vstack((arr1, arr2))
stacked_arr


array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# Calculating Mean and Standard Deviation
arr = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(arr)
std_dev = np.std(arr)
std_dev

1.4142135623730951

In [86]:
# Generating random numbers

random_array = np.random.rand(3, 3)
random_array

array([[0.78898994, 0.93354395, 0.55395418],
       [0.95443135, 0.82094341, 0.78625167],
       [0.98338218, 0.38489038, 0.81518275]])

# PANDAS

In [100]:
import pandas as pd

# Read a CSV file into a DataFrame
df = pd.read_csv('vgsales.csv')

# Display the first few rows of the DataFrame
print("First 5 rows of the DataFrame:")
print(df.head())

# Basic DataFrame Information
print("\nDataFrame Info:")
print(df.info())

# Descriptive Statistics
print("\nDescriptive Statistics:")
print(df.describe())

# Selecting Columns
selected_columns = df[['Name', 'Age']]
print("\nSelected Columns:")
print(selected_columns.head())

# Filtering Rows
filtered_rows = df[df['Age'] > 25]
print("\nFiltered Rows (Age > 25):")
print(filtered_rows.head())

# Grouping and Aggregation
grouped_data = df.groupby('Gender').agg({'Age': 'mean', 'Salary': 'sum'})
print("\nGrouped and Aggregated Data:")
print(grouped_data)

# Adding a New Column
df['Income_Category'] = pd.cut(df['Salary'], bins=[0, 50000, 100000, float('inf')], labels=['Low', 'Medium', 'High'])
print("\nDataFrame with New Column:")
print(df.head())

# Handling Missing Values
df.dropna(inplace=True)
print("\nDataFrame after Dropping Missing Values:")
print(df.head())

# Saving DataFrame to a New CSV file
df.to_csv('modified_example.csv', index=False)
print("\nDataFrame Saved to 'modified_example.csv'")


First 5 rows of the DataFrame:
   Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37  

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Col

KeyError: "['Age'] not in index"

In [99]:
count = 0
while count < 5:
    print(f'I start from here: {count}')
    count += 1
else:
    print('\n')
    print(count)

I start from here: 0
I start from here: 1
I start from here: 2
I start from here: 3
I start from here: 4


5


In [104]:
x = 10
while x == 10:
    print(f'even number between 1 to 10')
    if x%2 == 0:
        print(f'{x} is even number')
        if x == 10:
            break

even number between 1 to 10
10 is even number


In [105]:
c = [1,2,3,4,5,6,7,8,9,10]
for i in c:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [106]:
f = 'python'
for i in f:
    print(i)

p
y
t
h
o
n


In [107]:
for i in range(len(f)):
    print(i)

0
1
2
3
4
5


In [109]:
name = input('Wha is your name? ')
colour = input('What is your favorite colour? ')
print(f'{name} like\'s {colour}')

Al-amin like's White\\
